export const data = [
  {
    id: 1,
    name: "Saboor",
    position: "Intern",
    telegramId: "@SMmehrban ",
    stack: "Word Press",
  },
  {
    id: 2,
    name: "Mohammad Hojjat",
    position: "Team Leader",
    telegramId: "@EMHM2022 ",
    stack: "Frontend",
  },
  {
    id: 3,
    name: "Ali Reza",
    position: "Developer",
    telegramId: "@A_ZerstoRer ",
    stack: "Mobile",
  },
  {
    id: 4,
    name: "Asem",
    position: "Team Leader",
    telegramId: "@AQ725 ",
    stack: "Mobile",
  },
  {
    id: 5,
    name: "Fahim",
    position: "Developer",
    telegramId: "@Poya0795860286 ",
    stack: "Word Press",
  },
  {
    id: 7,
    name: "Farhang",
    position: "Team Leader",
    telegramId: "@farhangarab7 ",
    stack: "Backend",
  },
  {
    id: 6,
    name: "Mehdi",
    position: "Designer",
    telegramId: "@m9heb ",
    stack: "UI/UX Designer",
  },
  {
    id: 8,
    name: "Pooria",
    position: "Developer",
    telegramId: "@MohammedPooryaKhoshbin ",
    stack: "Frontend",
  },
  {
    id: 9,
    name: "Rashed",
    position: "Developer",
    telegramId: "@rahimirashed ",
    stack: "Mobile",
  },
  {
    id: 10,
    name: "Rohullah",
    position: "Intern",
    telegramId: "@Rohullah_Barak ",
    stack: "Word Press",
  },
  {
    id: 11,
    name: "Sajad",
    position: "Intern",
    telegramId: "@Sajad_Rad7 ",
    stack: "Backend",
  },
  {
    id: 12,
    name: "Rabea",
    position: "Team Leader",
    telegramId: "@m_r786 ",
    stack: "Backend",
  },
  {
    id: 13,
    name: "Mohebullah",
    position: "Developer",
    telegramId: "@Mohebullah50",
    stack: "Backend",
  },
];

export default data;
